-- Track every click on the WhatsApp button on PostCard.
create table if not exists public.whatsapp_click_logs (
  id bigint generated by default as identity primary key,
  user_id uuid null references auth.users(id) on delete set null,
  guest_token text null,
  target_profile_id text not null references public.profiles(id) on delete cascade,
  post_id uuid null references public.cars(id) on delete set null,
  source text not null default 'unknown',
  user_agent text null,
  created_at timestamptz not null default now()
);

create index if not exists idx_whatsapp_click_logs_created_at
  on public.whatsapp_click_logs (created_at desc);

create index if not exists idx_whatsapp_click_logs_target_profile_id
  on public.whatsapp_click_logs (target_profile_id, created_at desc);

create index if not exists idx_whatsapp_click_logs_user_id
  on public.whatsapp_click_logs (user_id);

create index if not exists idx_whatsapp_click_logs_guest_token
  on public.whatsapp_click_logs (guest_token)
  where guest_token is not null;

alter table public.whatsapp_click_logs enable row level security;
