-- Track each visitor session entry while keeping daily unique visitor summaries separate.

create table if not exists public.visitor_visit_logs (
  id bigint generated by default as identity primary key,
  visit_date date not null,
  actor_type text not null check (actor_type in ('user', 'guest')),
  actor_key text not null,
  user_id text null references public.profiles(id) on delete cascade,
  guest_token text null,
  session_key text not null,
  entry_path text not null default '/',
  user_agent text null,
  visited_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint visitor_visit_logs_actor_identity_check check (
    (actor_type = 'user' and user_id is not null and guest_token is null)
    or
    (actor_type = 'guest' and guest_token is not null and user_id is null)
  )
);

create unique index if not exists idx_visitor_visit_logs_dedup
  on public.visitor_visit_logs (visit_date, actor_type, actor_key, session_key);

create index if not exists idx_visitor_visit_logs_visit_date
  on public.visitor_visit_logs (visit_date desc, visited_at desc);

create index if not exists idx_visitor_visit_logs_actor_key
  on public.visitor_visit_logs (actor_type, actor_key, visited_at desc);

create index if not exists idx_visitor_visit_logs_user_id
  on public.visitor_visit_logs (user_id, visited_at desc)
  where user_id is not null;

create index if not exists idx_visitor_visit_logs_guest_token
  on public.visitor_visit_logs (guest_token, visited_at desc)
  where guest_token is not null;

comment on table public.visitor_visit_logs is
  'เก็บการเข้าใช้งานแต่ละครั้งแบบ session-level แยกจากตาราง daily unique visitor';

comment on column public.visitor_visit_logs.visit_date is
  'วันตาม timezone Asia/Bangkok (+07) จากฝั่ง API';

comment on column public.visitor_visit_logs.session_key is
  'session key จากฝั่ง client ใช้ dedupe การนับซ้ำใน session เดียว';

alter table public.visitor_visit_logs enable row level security;