-- นับจำนวนการกดแชร์จากเมนูโพสต์
-- ไม่เก็บว่าใครกด เก็บแค่จำนวนครั้ง (เฉพาะ Guest และ User ทั่วไป ไม่นับ admin/sub-account)
create table if not exists public.share_clicks (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

create index if not exists idx_share_clicks_created_at
  on public.share_clicks (created_at desc);

alter table public.share_clicks enable row level security;
