-- Track every click on the image download button.
create table if not exists public.download_click_logs (
  id bigint generated by default as identity primary key,
  user_id uuid null references auth.users(id) on delete set null,
  source text not null default 'unknown',
  user_agent text null,
  created_at timestamptz not null default now()
);

create index if not exists idx_download_click_logs_created_at
  on public.download_click_logs (created_at desc);

create index if not exists idx_download_click_logs_user_id
  on public.download_click_logs (user_id);

alter table public.download_click_logs enable row level security;
