CREATE TABLE IF NOT EXISTS public.post_compare_lists (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  post_id TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  CONSTRAINT post_compare_lists_user_post_key UNIQUE (user_id, post_id)
);

CREATE INDEX IF NOT EXISTS idx_post_compare_lists_user_created_at
  ON public.post_compare_lists (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_post_compare_lists_post_id
  ON public.post_compare_lists (post_id);

COMMENT ON TABLE public.post_compare_lists IS 'Posts pinned by a signed-in actor for price comparison.';

ALTER TABLE public.post_compare_lists ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own compare list" ON public.post_compare_lists;
CREATE POLICY "Users can view own compare list"
  ON public.post_compare_lists
  FOR SELECT
  TO authenticated
  USING (
    auth.uid()::text = user_id
    OR EXISTS (
      SELECT 1
      FROM public.profiles
      WHERE public.profiles.id = public.post_compare_lists.user_id
        AND public.profiles.parent_admin_id = auth.uid()::text
    )
  );

DROP POLICY IF EXISTS "Users can create own compare list" ON public.post_compare_lists;
CREATE POLICY "Users can create own compare list"
  ON public.post_compare_lists
  FOR INSERT
  TO authenticated
  WITH CHECK (
    auth.uid()::text = user_id
    OR EXISTS (
      SELECT 1
      FROM public.profiles
      WHERE public.profiles.id = public.post_compare_lists.user_id
        AND public.profiles.parent_admin_id = auth.uid()::text
    )
  );

DROP POLICY IF EXISTS "Users can update own compare list" ON public.post_compare_lists;
CREATE POLICY "Users can update own compare list"
  ON public.post_compare_lists
  FOR UPDATE
  TO authenticated
  USING (
    auth.uid()::text = user_id
    OR EXISTS (
      SELECT 1
      FROM public.profiles
      WHERE public.profiles.id = public.post_compare_lists.user_id
        AND public.profiles.parent_admin_id = auth.uid()::text
    )
  )
  WITH CHECK (
    auth.uid()::text = user_id
    OR EXISTS (
      SELECT 1
      FROM public.profiles
      WHERE public.profiles.id = public.post_compare_lists.user_id
        AND public.profiles.parent_admin_id = auth.uid()::text
    )
  );

DROP POLICY IF EXISTS "Users can delete own compare list" ON public.post_compare_lists;
CREATE POLICY "Users can delete own compare list"
  ON public.post_compare_lists
  FOR DELETE
  TO authenticated
  USING (
    auth.uid()::text = user_id
    OR EXISTS (
      SELECT 1
      FROM public.profiles
      WHERE public.profiles.id = public.post_compare_lists.user_id
        AND public.profiles.parent_admin_id = auth.uid()::text
    )
  );