export const MOTION_EASING = {
  EMPHASIZED: 'cubic-bezier(0.22, 1, 0.36, 1)',
  STANDARD: 'cubic-bezier(0.4, 0, 0.2, 1)',
  EASE_OUT: 'ease-out',
} as const;

export const MOTION_DURATION_MS = {
  HOME_CHROME_TRANSFORM: 300,
  HOME_CHROME_SHADOW: 240,
  APP_HEADER_TRANSFORM: 150,
  APP_HEADER_SHADOW: 150,
} as const;

export const MOTION_TRANSITIONS = {
  HOME_CHROME_TRANSFORM: `transform ${MOTION_DURATION_MS.HOME_CHROME_TRANSFORM}ms ${MOTION_EASING.EMPHASIZED}`,
  HOME_CHROME:
    `transform ${MOTION_DURATION_MS.HOME_CHROME_TRANSFORM}ms ${MOTION_EASING.EMPHASIZED}, ` +
    `box-shadow ${MOTION_DURATION_MS.HOME_CHROME_SHADOW}ms ${MOTION_EASING.EASE_OUT}`,
  APP_HEADER:
    `transform ${MOTION_DURATION_MS.APP_HEADER_TRANSFORM}ms ${MOTION_EASING.STANDARD}, ` +
    `box-shadow ${MOTION_DURATION_MS.APP_HEADER_SHADOW}ms ${MOTION_EASING.EASE_OUT}`,
} as const;
