/**
 * Aggregator: combines meta + all brand JSON files.
 * Generated by scripts/split-cars.mjs - do not edit manually.
 */

import meta from './meta.json';

import aion from './brands/aion.json';
import aston_martin from './brands/aston-martin.json';
import audi from './brands/audi.json';
import avatr from './brands/avatr.json';
import baic from './brands/baic.json';
import bentley from './brands/bentley.json';
import bmw from './brands/bmw.json';
import byd from './brands/byd.json';
import cadillac from './brands/cadillac.json';
import changan from './brands/changan.json';
import chery from './brands/chery.json';
import chevrolet from './brands/chevrolet.json';
import daehan from './brands/daehan.json';
import deepal from './brands/deepal.json';
import dfsk from './brands/dfsk.json';
import dongfeng from './brands/dongfeng.json';
import ferrari from './brands/ferrari.json';
import ford from './brands/ford.json';
import foton from './brands/foton.json';
import gac from './brands/gac.json';
import geely from './brands/geely.json';
import gmc from './brands/gmc.json';
import haval from './brands/haval.json';
import hino from './brands/hino.json';
import honda from './brands/honda.json';
import hummer from './brands/hummer.json';
import hyundai from './brands/hyundai.json';
import icar from './brands/icar.json';
import isuzu from './brands/isuzu.json';
import jac from './brands/jac.json';
import jaguar from './brands/jaguar.json';
import jeep from './brands/jeep.json';
import jmc from './brands/jmc.json';
import kia from './brands/kia.json';
import lamborghini from './brands/lamborghini.json';
import land_rover from './brands/land-rover.json';
import leapmotor from './brands/leapmotor.json';
import lexus from './brands/lexus.json';
import lotus from './brands/lotus.json';
import maserati from './brands/maserati.json';
import mazda from './brands/mazda.json';
import mclaren from './brands/mclaren.json';
import mercedes_benz from './brands/mercedes-benz.json';
import mg from './brands/mg.json';
import mitsubishi from './brands/mitsubishi.json';
import neta from './brands/neta.json';
import nissan from './brands/nissan.json';
import ora from './brands/ora.json';
import peugeot from './brands/peugeot.json';
import porsche from './brands/porsche.json';
import rolls_royce from './brands/rolls-royce.json';
import suzuki from './brands/suzuki.json';
import tank from './brands/tank.json';
import tesla from './brands/tesla.json';
import toyota from './brands/toyota.json';
import vinfast from './brands/vinfast.json';
import volkswagen from './brands/volkswagen.json';
import volvo from './brands/volvo.json';
import wuling from './brands/wuling.json';
import xiaomi from './brands/xiaomi.json';
import xpeng from './brands/xpeng.json';
import zeekr from './brands/zeekr.json';

const brands = [aion, aston_martin, audi, avatr, baic, bentley, bmw, byd, cadillac, changan, chery, chevrolet, daehan, deepal, dfsk, dongfeng, ferrari, ford, foton, gac, geely, gmc, haval, hino, honda, hummer, hyundai, icar, isuzu, jac, jaguar, jeep, jmc, kia, lamborghini, land_rover, leapmotor, lexus, lotus, maserati, mazda, mclaren, mercedes_benz, mg, mitsubishi, neta, nissan, ora, peugeot, porsche, rolls_royce, suzuki, tank, tesla, toyota, vinfast, volkswagen, volvo, wuling, xiaomi, xpeng, zeekr];

const carsData = { meta, brands };
export default carsData;
