#!/usr/bin/env node
/**
 * Splits data/cars.json into individual brand files in data/brands/
 * and creates data/meta.json + data/index.ts aggregator.
 *
 * Usage:
 *   node scripts/split-cars.mjs          - Full split from cars.json
 *   node scripts/split-cars.mjs --merge  - Regenerate index.ts from brands/ (when adding new brand)
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const dataDir = join(root, 'data');
const brandsDir = join(dataDir, 'brands');

const mergeOnly = process.argv.includes('--merge');

let brandIds;

if (mergeOnly && existsSync(brandsDir)) {
  // Regenerate index.ts from existing brands/
  brandIds = readdirSync(brandsDir)
    .filter((f) => f.endsWith('.json'))
    .map((f) => f.replace(/\.json$/, ''))
    .sort((a, b) => a.localeCompare(b));
  if (!existsSync(join(dataDir, 'meta.json'))) {
    console.error('data/meta.json not found. Run full split first.');
    process.exit(1);
  }
} else {
  const carsPath = join(dataDir, 'cars.json');
  if (!existsSync(carsPath)) {
    console.error('data/cars.json not found.');
    process.exit(1);
  }
  const raw = readFileSync(carsPath, 'utf-8');
  const data = JSON.parse(raw);
  const { meta, brands } = data;

  if (!existsSync(brandsDir)) {
    mkdirSync(brandsDir, { recursive: true });
  }

  writeFileSync(join(dataDir, 'meta.json'), JSON.stringify(meta, null, 2), 'utf-8');

  brandIds = [];
  for (const brand of brands) {
    const id = brand.brandId;
    brandIds.push(id);
    const outPath = join(brandsDir, `${id}.json`);
    writeFileSync(outPath, JSON.stringify(brand, null, 2), 'utf-8');
  }
}

// Generate data/index.ts that imports all brands and exports carsData
const imports = brandIds
  .map((id) => `import ${id.replace(/-/g, '_')} from './brands/${id}.json';`)
  .join('\n');

const brandVars = brandIds.map((id) => id.replace(/-/g, '_')).join(', ');
const brandsArray = `[${brandVars}]`;

const indexContent = `/**
 * Aggregator: combines meta + all brand JSON files.
 * Generated by scripts/split-cars.mjs - do not edit manually.
 */

import meta from './meta.json';

${imports}

const brands = ${brandsArray};

const carsData = { meta, brands };
export default carsData;
`;

writeFileSync(join(dataDir, 'index.ts'), indexContent, 'utf-8');

console.log(mergeOnly
  ? `Regenerated data/index.ts from ${brandIds.length} brands`
  : `Split ${brandIds.length} brands into data/brands/`);
console.log('Created data/meta.json and data/index.ts');
